let level1;

function initLevel() {

    level1 = new Level(
        [
            new Chicken(820),
            new Chicken(900),
            new Chicken(1300),
            new Chicken(1700),
            new Chicken(2100),
            new Chicken(2550),
            new Chicken(3100),
            new Chicken(4200),
            new Chicken(2600),
            new Chicken(6000),
            new ChickenSmall(1050),
            new ChickenSmall(1900),
            new ChickenSmall(4100),
            new ChickenSmall(3700),
            new ChickenSmall(3200),
            new ChickenSmall(3800),
            new ChickenSmall(5100),
            new ChickenSmall(5600),
            new Endboss(),
        ],
        [
            new Cloud(0, 50, 0),
            new Cloud(480, 45, 1),
            new Cloud(1080, 55, 0),
            new Cloud(1630, 60, 1),
            new Cloud(2180, 48, 0),
            new Cloud(2780, 63, 1),
        ],
        [
            new BackgroundObject('./assets/img/5_background/layers/air.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/air.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/air.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', 719),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 719 * 4),
        ],
        [
            new Bottle(240),
            new Bottle(520),
            new Bottle(680),
            new Bottle(750),
            new Bottle(880),
            new Bottle(960),
            new Bottle(1030),
            new Bottle(1150),
            new Bottle(1240),
            new Bottle(1320),
            new Bottle(1410),
            new Bottle(1530),
            new Bottle(1610),
            new Bottle(1720),
            new Bottle(1830),
            new Bottle(1940),
            new Bottle(2050),
            new Bottle(2180),
            new Bottle(2320),
        ],
        [
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
        ]
    );
}